apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Service.name }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: {{ .Values.Service.app }}
  type: NodePort  
  ports:
    - name: httpport
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.Service.nodePort }}
    - name: jnlpport
      port: 50000
      targetPort: 50000
